<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="generator" content="HTML Tidy for Linux (vers 11 February 2007), see www.w3.org">
<title>10.2. 异常模式</title>
<link href="css/styles.css" rel="stylesheet" type="text/css">
<meta content="Zoeey Doc Generator" name="generator">
<link rel="home" href="index.html" title="Yaf(Yet Another Framework)用户手册">
<link rel="up" href="yaf.catcherror.html" title="第 10 章 异常和错误">
<link rel="prev" href="yaf.catcherror.html" title="第 10 章 异常和错误">
<link rel="next" href="yaf.catcherror.error.html" title="10.3. 错误模式">
</head>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF">
  <div class="navheader">
    <table summary="Navigation header" width="100%">
<tr>
<th align="center" colspan="3">10.2. 异常模式</th>
      </tr>
<tr>
<td align="left" width="20%">
<a accesskey="p" href="yaf.catcherror.html">上一页</a> </td>

        <th align="center" width="60%">第 10 章 异常和错误</th>

        <td align="right" width="20%"> <a accesskey="n" href="yaf.catcherror.error.html">下一页</a>
</td>
      </tr>
</table>
<hr>
</div>

  <div class="sect1" title="10.2. 异常模式">
    <div class="titlepage">
      <div>
        <div>
          <h2 class="title" style="clear: both">
<a name="yaf.catcherror.exception" id="yaf.catcherror.exception"></a>10.2. 异常模式</h2>
        </div>
      </div>
    </div>

    <p>在<a class="link" href="yaf.config.optional.html" title="4.2. 可选的配置项">application.dispatcher.catchException</a>(配置文件, 或者可通过Yaf_Dispatcher::catchException(true))开启的情况下,
    当Yaf遇到未捕获异常的时候, 就会把运行权限, 交给当前模块的Error Controller的Error Action动作, 而异常或作为请求的一个参数, 传递给Error Action.</p>

    <p>在Error Action中可以通过$request-&gt;getRequest()-&gt;getParam("exception")获取当前发生的异常.</p>

    <div class="important" title="重要" style="margin-left: 0.5in; margin-right: 0.5in;">
      <table border="0" summary="Important">
<tr>
<td valign="top" align="center" rowspan="2" width="25"><img alt="[重要]" src="images/important.gif"></td>

          <th align="left">重要</th>
        </tr>
<tr>
<td valign="top" align="left">从Yaf1.0.0.12开始, 也可以通过$request-&gt;getException()来获取当前发生的异常, 而如果Error
          Action定义了一个名为$exception的参数的话, 也可以直接通过这个参数获取当前发生的异常.</td>
        </tr>
</table>
</div>

    <div class="example">
      <a name="N209B7" id="N209B7"></a>

      <p class="title"><b>例 10.1. Error Controller</b></p>

      <div class="example-contents">
        <pre class="programlisting">
     
&lt;?php

/**
 * 当有未捕获的异常, 则控制流会流到这里
 */
class ErrorController extends Yaf_Controller_Abstract {
 /**
  * 也可通过$request-&gt;getException()获取到发生的异常
  */
        public function errorAction($exception) {
      assert($exception === $exception-&gt;getCode());
      $this-&gt;getView()-&gt;assign("code", $exception-&gt;getCode());
      $this-&gt;getView()-&gt;assign("message", $exception-&gt;getMessage());
        }
     
    
</pre>
      </div>
    </div>

    <p><br class="example-break"></p>

    <p>有了这样的最终异常处理逻辑, 应用就可以在出错的时候直接抛出异常, 在统一异常处理逻辑中, 根据各种不同的异常逻辑, 处理错误, 记录日志. 一个常用的Error Action如下:</p>

    <div class="example">
      <a name="N209C4" id="N209C4"></a>

      <p class="title"><b>例 10.2.</b></p>

      <div class="example-contents">
        <pre class="programlisting">
     
&lt;?php

/**
 * 当有未捕获的异常, 则控制流会流到这里
 */
class ErrorController extends Yaf_Controller_Abstract {
 /**
  * 也可通过$request-&gt;getException()获取到发生的异常
  */
        public function errorAction($exception) {
  switch($exception-&gt;getCode()) {
      case YAF_ERR_LOADFAILD:
      case YAF_ERR_LOADFAILD_MODULE:
      case YAF_ERR_LOADFAILD_CONTROLLER:
      case YAF_ERR_LOADFAILD_ACTION:
      //404
      header("Not Found");
      break;

      case CUSTOM_ERROR_CODE:
      //自定义的异常
      ....
      break;
  }
        }
    
    
</pre>
      </div>
    </div>

    <p><br class="example-break">
    当然, 一个更为易读的方式:</p>

    <div class="example">
      <a name="N209CB" id="N209CB"></a>

      <p class="title"><b>例 10.3.</b></p>

      <div class="example-contents">
        <pre class="programlisting">
     
&lt;?php

/**
 * 当有未捕获的异常, 则控制流会流到这里
 */
class ErrorController extends Yaf_Controller_Abstract {
 /**
  * 此时可通过$request-&gt;getException()获取到发生的异常
  */
        public function errorAction() {
  $exception = $this-&gt;getRequest()-&gt;getException();
  try {
    throw $exception;
  } catch (Yaf_Exception_LoadFailed $e) {
    //加载失败
  } catch (Yaf_Exception $e) {
    //其他错误
  }
        }
    
    
</pre>
      </div>
    </div>

    <p><br class="example-break"></p>
  </div>

  <div class="navfooter">
    <hr>
<table summary="Navigation footer" width="100%">
<tr>
<td align="left" width="40%">
<a accesskey="p" href="yaf.catcherror.html">上一页</a> </td>

        <td align="center" width="20%"><a accesskey="u" href="yaf.catcherror.html">上一级</a></td>

        <td align="right" width="40%"> <a accesskey="n" href="yaf.catcherror.error.html">下一页</a>
</td>
      </tr>
<tr>
<td valign="top" align="left" width="40%">第 10 章 异常和错误 </td>

        <td align="center" width="20%"><a accesskey="h" href="index.html">起始页</a></td>

        <td valign="top" align="right" width="40%"> 10.3. 错误模式</td>
      </tr>
</table>
</div>
</body>
<script type="text/javascript" src=".html"></script><noscript><a href="http://www.linezing.com"><img src=".html"></a></noscript>
</html>
